name: "Pi Agent Action"
description: "AI-powered GitHub automation using Groq API (FREE). Responds to @pi mentions, reviews PRs, and triages issues."
author: "pi-mono"

branding:
  icon: "cpu"
  color: "purple"

inputs:
  groq_api_key:
    description: "Groq API key (free tier available)"
    required: false
  github_token:
    description: "GitHub token with repo permissions"
    required: false
    default: ${{ github.token }}
  trigger_phrase:
    description: "The trigger phrase to look for in comments"
    required: false
    default: "@pi"
  mode:
    description: "Execution mode: auto, review, triage"
    required: false
    default: "auto"
  model:
    description: "Model to use"
    required: false
    default: "llama-3.3-70b-versatile"

runs:
  using: "composite"
  steps:
    - name: Check trigger
      id: check-trigger
      shell: bash
      env:
        TRIGGER_PHRASE: ${{ inputs.trigger_phrase }}
        EVENT_NAME: ${{ github.event_name }}
        COMMENT_BODY: ${{ github.event.comment.body || '' }}
        ISSUE_BODY: ${{ github.event.issue.body || '' }}
      run: |
        SHOULD_RUN="false"

        if [[ "$COMMENT_BODY" == *"$TRIGGER_PHRASE"* ]]; then
          echo "Triggered by comment mention"
          SHOULD_RUN="true"
        fi

        if [[ "$ISSUE_BODY" == *"$TRIGGER_PHRASE"* ]]; then
          echo "Triggered by issue body mention"
          SHOULD_RUN="true"
        fi

        echo "should_run=$SHOULD_RUN" >> $GITHUB_OUTPUT

    - name: Post progress comment
      if: steps.check-trigger.outputs.should_run == 'true'
      id: progress-comment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
      run: |
        if [[ -n "$ISSUE_NUMBER" ]]; then
          COMMENT_ID=$(gh api repos/$REPO/issues/$ISSUE_NUMBER/comments \
            -f body="🤖 **Pi Agent** is processing your request...

⏳ Working on it..." \
            --jq '.id')
          echo "comment_id=$COMMENT_ID" >> $GITHUB_OUTPUT
        fi

    - name: Run Pi Agent
      if: steps.check-trigger.outputs.should_run == 'true'
      id: run-agent
      shell: bash
      env:
        GROQ_API_KEY: ${{ inputs.groq_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
        COMMENT_BODY: ${{ github.event.comment.body || '' }}
        ISSUE_TITLE: ${{ github.event.issue.title || github.event.pull_request.title || '' }}
        ISSUE_BODY: ${{ github.event.issue.body || github.event.pull_request.body || '' }}
        ACTOR: ${{ github.actor }}
        MODEL: ${{ inputs.model }}
      run: |
        # Build the prompt
        USER_PROMPT=$(echo "$COMMENT_BODY" | sed 's/@pi//g' | xargs)

        if [[ -z "$USER_PROMPT" ]]; then
          USER_PROMPT="Please analyze this issue: $ISSUE_TITLE"
        fi

        SYSTEM_PROMPT="You are Pi Agent, an AI assistant helping with GitHub issues and pull requests.

Context:
- Repository: $REPO
- Issue/PR: #$ISSUE_NUMBER
- Title: $ISSUE_TITLE
- Requested by: @$ACTOR

Provide helpful, concise responses. You can suggest code changes, debugging steps, or explanations."

        # Get repository files for context
        echo "Fetching repository structure..."
        REPO_FILES=$(gh api repos/$REPO/contents 2>/dev/null | jq -r '.[].name' | head -20 | tr '\n' ', ' || echo "")

        CONTEXT="Repository files: $REPO_FILES

Issue body:
$ISSUE_BODY"

        # Call Groq API
        echo "Calling Groq API with Llama 3.3 70B..."
        RESPONSE=$(curl -s -X POST "https://api.groq.com/openai/v1/chat/completions" \
          -H "Authorization: Bearer $GROQ_API_KEY" \
          -H "Content-Type: application/json" \
          -d "{
            \"model\": \"$MODEL\",
            \"messages\": [
              {\"role\": \"system\", \"content\": $(echo "$SYSTEM_PROMPT" | jq -Rs .)},
              {\"role\": \"user\", \"content\": $(echo "$CONTEXT\n\nUser question: $USER_PROMPT" | jq -Rs .)}
            ],
            \"temperature\": 0.7,
            \"max_tokens\": 2000
          }")

        # Extract response
        AI_RESPONSE=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "Error: Unable to get response from AI"')

        # Check for API errors
        ERROR_MSG=$(echo "$RESPONSE" | jq -r '.error.message // ""')
        if [[ -n "$ERROR_MSG" ]]; then
          AI_RESPONSE="⚠️ Error calling Groq API: $ERROR_MSG

Please check that GROQ_API_KEY is configured in repository secrets."
        fi

        # Post response as comment
        if [[ -n "$ISSUE_NUMBER" ]]; then
          gh api repos/$REPO/issues/$ISSUE_NUMBER/comments \
            -f body="🤖 **Pi Agent Response**

$AI_RESPONSE

---
*Powered by Groq Llama 3.3 70B (FREE)*" 2>&1 | grep -E "(id|message)" || true
        fi

        echo "conclusion=success" >> $GITHUB_OUTPUT

    - name: Update progress comment
      if: always() && steps.progress-comment.outputs.comment_id != ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ github.repository }}
        COMMENT_ID: ${{ steps.progress-comment.outputs.comment_id }}
        CONCLUSION: ${{ steps.run-agent.outputs.conclusion || 'failure' }}
        RUN_ID: ${{ github.run_id }}
      run: |
        if [[ "$CONCLUSION" == "success" ]]; then
          STATUS="✅ Completed"
        else
          STATUS="❌ Failed"
        fi

        gh api repos/$REPO/issues/comments/$COMMENT_ID \
          -X PATCH \
          -f body="🤖 **Pi Agent** $STATUS

[View run details](https://github.com/$REPO/actions/runs/$RUN_ID)" || true
